document.writeln("<div class=\"container\">");
document.writeln("<div class=\"row\">");
document.writeln("<nav class=\"navbar navbar-expand-md navbar-dark\">");
document.writeln("  <!-- Brand -->");
document.writeln("  <a class=\"navbar-brand\"><img src=\"https://13511974.s21i.faiusr.com/4/10/ABUIABAEGAAg1t7XrwYo4J2EmAUw1QU40gE.png\" height=\"70px\"></a>");
document.writeln(" ");
document.writeln("  <!-- Toggler/collapsibe Button -->");
document.writeln("  <a class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapsibleNavbar\">");
document.writeln("    <span class=\"navbar-toggler-icon\"></span>");
document.writeln("  </a>");
document.writeln(" ");
document.writeln("  <!-- Navbar links -->");
document.writeln("  <div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\">");
document.writeln("    <ul class=\"navbar-nav\">");
document.writeln("      <li class=\"nav-item\">");
document.writeln("        <a class=\"nav-link\" href=\"/itim/\">首页</a>");
document.writeln("      </li>");
document.writeln("      <li class=\"nav-item\">");
document.writeln("        <a class=\"nav-link\" href=\"/itim/about.htm\">关于本项目</a>");
document.writeln("      </li> ");
document.writeln("<!-- Dropdown -->");
document.writeln("    <li class=\"nav-item dropdown\">");
document.writeln("      <a class=\"nav-link dropdown-toggle\" id=\"navbardrop\" data-bs-toggle=\"dropdown\">");
document.writeln("        贡献本项目");
document.writeln("      </a>");
document.writeln("      <div class=\"dropdown-menu\">");
document.writeln("        <a class=\"dropdown-item\" href=\"/itim/contribute.htm\">投稿上榜</a>");
document.writeln("        <a class=\"dropdown-item\" href=\"/itim/contrilist.htm\">贡献列表</a>");
document.writeln("      </div>");
document.writeln("    </li>");
document.writeln("");
document.writeln("    </ul>");
document.writeln("  </div> ");
document.writeln("</nav>");
document.writeln("</div>");
document.writeln("</div>");
